---
- name: ensure packages required are installed
  yum: 
    name="{{ item }}"
    state=latest
  with_items:
    - gzip
    - unzip
    - git
    - java-1.7.0-openjdk

- name: create dba group
  group: 
    name=dba
    state=present

- name: create oracle user
  user: 
    name=oracle 
    shell=/bin/bash 
    home=/home/oracle 
    groups=dba 
    append=yes 
    createhome=yes
    state=present

- name: add oracle to sudoers
  lineinfile:
  args:
    dest: "/etc/sudoers.d/oracle"
    create: yes
    state: present
    line: "oracle        ALL=(ALL)       NOPASSWD: ALL"
    mode: "0440"

- name: create endeca_root directory
  file:
  args:
    state: directory
    path: "{{ endeca_root }}"
    owner: "oracle"
    group: "dba"
    mode: 0755

- name: create pid directory
  file:
  args:
    state: directory
    path: "{{ pid_dir }}"
    owner: "oracle"
    group: "dba"
    mode: 0755
